$:.unshift("/Library/RubyMotion/lib")

platform = ENV.fetch('platform', 'osx')
testing  = true if ARGV.join(' ') =~ /spec/

require "motion/project/template/#{platform}"
require 'rubygems'

begin
  require 'bundler'
  testing ? Bundler.require(:default, :spec) : Bundler.require
rescue LoadError
end

require 'bacon-expect' if testing

Motion::Project::App.setup do |app|
  app.name        = 'motion-markdown-it'
  app.identifier  = 'com.motion-gemtest.motion-markdown-it'

  app.detect_dependencies = true
end
